"""create candidates and candidate_events

Revision ID: 0e3646af2844
Revises: 
Create Date: 2026-09-22 12:31:14.233450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e3646af2844'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('decoded_domain', sa.String(length=255), nullable=True),
    sa.Column('matched_brand', sa.String(length=255), nullable=False),
    sa.Column('detected_at', sa.String(length=40), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('visual_similarity', sa.Float(), nullable=True),
    sa.Column('has_login_form', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_matched_brand'), ['matched_brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_risk_level'), ['risk_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_status'), ['status'], unique=False)

    op.create_table('candidate_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('old_value', sa.String(length=100), nullable=True),
    sa.Column('new_value', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_events_candidate_id'), ['candidate_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_events_candidate_id'))

    op.drop_table('candidate_events')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_candidates_risk_score'))
        batch_op.drop_index(batch_op.f('ix_candidates_risk_level'))
        batch_op.drop_index(batch_op.f('ix_candidates_matched_brand'))
        batch_op.drop_index(batch_op.f('ix_candidates_domain'))
        batch_op.drop_index(batch_op.f('ix_candidates_detected_at'))

    op.drop_table('candidates')
    # ### end Alembic commands ###
