"""add ssim and combined similarity

Revision ID: 29d97da5f0ce
Revises: 2ad17e600cb0
Create Date: 2026-09-22 14:27:18.853746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29d97da5f0ce'
down_revision: Union[str, Sequence[str], None] = '2ad17e600cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ssim_similarity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('combined_similarity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('combined_similarity')
        batch_op.drop_column('ssim_similarity')

    # ### end Alembic commands ###
