"""add phase 3 enrichment signals

Revision ID: 2ad17e600cb0
Revises: 0e3646af2844
Create Date: 2026-09-22 12:56:15.074427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad17e600cb0'
down_revision: Union[str, Sequence[str], None] = '0e3646af2844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_mx', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_spf', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('has_dmarc', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ssl_issuer', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ssl_san_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ssl_validity_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ssl_is_free_or_short_lived', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('favicon_hash', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('favicon_hash')
        batch_op.drop_column('ssl_is_free_or_short_lived')
        batch_op.drop_column('ssl_validity_days')
        batch_op.drop_column('ssl_san_count')
        batch_op.drop_column('ssl_issuer')
        batch_op.drop_column('has_dmarc')
        batch_op.drop_column('has_spf')
        batch_op.drop_column('has_mx')

    # ### end Alembic commands ###
